# Generated by Django 3.2.5 on 2021-07-31 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210801_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='cateegory',
            new_name='category',
        ),
    ]
